<?php
require_once 'db_connection.php';

// ======================================================
// LOAD DOMPDF
// ======================================================
require_once '../vendor/autoload.php';
use Dompdf\Dompdf;
use Dompdf\Options;

// ======================================================
// CHECK BOQ ID
// ======================================================
if(!isset($_GET['id'])) {

    die("Invalid BOQ ID");
}

$boq_id = (int) $_GET['id'];

// ======================================================
// FETCH BOQ DETAILS
// ======================================================
$stmt = $conn->prepare("
    SELECT *
    FROM boq
    WHERE boq_id = ?
");

$stmt->bind_param("i", $boq_id);
$stmt->execute();

$result = $stmt->get_result();

if($result->num_rows == 0) {

    die("BOQ not found");
}

$boq = $result->fetch_assoc();

// ======================================================
// FETCH BOQ ITEMS
// ======================================================
$itemStmt = $conn->prepare("
    SELECT *
    FROM boq_items
    WHERE boq_id = ?
");

$itemStmt->bind_param("i", $boq_id);
$itemStmt->execute();

$itemsResult = $itemStmt->get_result();

// ======================================================
// HTML CONTENT
// ======================================================
$html = '

<style>

body {
    font-family: Arial, sans-serif;
    font-size: 12px;
    color: #333;
}

.header {
    text-align: center;
    margin-bottom: 25px;
}

.header h1 {
    margin: 0;
    color: #ff7b00;
}

.header p {
    margin-top: 5px;
    color: #666;
}

.info-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 20px;
}

.info-table td {
    border: 1px solid #ddd;
    padding: 10px;
}

.boq-table {
    width: 100%;
    border-collapse: collapse;
}

.boq-table th {
    background-color: #ff7b00;
    color: #fff;
    padding: 10px;
    border: 1px solid #ddd;
}

.boq-table td {
    border: 1px solid #ddd;
    padding: 8px;
}

.footer {
    margin-top: 40px;
    text-align: right;
    font-size: 11px;
    color: #777;
}

</style>

<div class="header">

    <h1>Bill Of Quantities</h1>

    <p>ShowcaseIT Stock Management System</p>

</div>

<table class="info-table">

    <tr>
        <td><strong>BOQ Number</strong></td>
        <td>'.$boq['boq_number'].'</td>
    </tr>

    <tr>
        <td><strong>Order Number</strong></td>
        <td>'.$boq['order_number'].'</td>
    </tr>

    <tr>
        <td><strong>Name Of Event</strong></td>
        <td>'.$boq['event_name'].'</td>
    </tr>

    <tr>
        <td><strong>Location</strong></td>
        <td>'.$boq['location'].'</td>
    </tr>

    <tr>
        <td><strong>Date Created</strong></td>
        <td>'.$boq['created_at'].'</td>
    </tr>

</table>

<table class="boq-table">

    <thead>

        <tr>

            <th style="width:5%">#</th>
            <th style="width:25%">Product Name</th>
            <th style="width:45%">Description</th>
            <th style="width:10%">Unit</th>
            <th style="width:15%">Quantity</th>

        </tr>

    </thead>

    <tbody>
';

$count = 1;

while($item = $itemsResult->fetch_assoc()) {

    $html .= '

        <tr>

            <td>'.$count++.'</td>

            <td>
                '.htmlspecialchars($item['product_name']).'
            </td>

            <td>
                '.htmlspecialchars($item['description']).'
            </td>

            <td>
                '.htmlspecialchars($item['unit']).'
            </td>

            <td>
                '.htmlspecialchars($item['quantity']).'
            </td>

        </tr>

    ';
}

$html .= '

    </tbody>

</table>

<div class="footer">

    Generated by ShowcaseIT

</div>

';

// ======================================================
// DOMPDF SETTINGS
// ======================================================
$options = new Options();

$options->set('isRemoteEnabled', true);

$dompdf = new Dompdf($options);

// ======================================================
// LOAD HTML
// ======================================================
$dompdf->loadHtml($html);

// ======================================================
// PAPER SETTINGS
// ======================================================
$dompdf->setPaper('A4', 'portrait');

// ======================================================
// RENDER PDF
// ======================================================
$dompdf->render();

// ======================================================
// DOWNLOAD PDF
// ======================================================
$fileName = "BOQ_" . $boq['boq_number'] . ".pdf";

$dompdf->stream($fileName, [
    "Attachment" => true
]);

exit();
?>