// Replaces downloadBOQ.php's DOMPDF rendering with Puppeteer. The HTML/CSS layout is preserved
// exactly — only the rendering engine changed.

import type { Boq, BoqItem } from '#prisma-client'

// puppeteer v25+ ships ESM-only; the server is CommonJS, so it must be loaded via dynamic import().
const loadPuppeteer = () => import('puppeteer').then((m) => m.default)
type PuppeteerModule = Awaited<ReturnType<typeof loadPuppeteer>>
type Browser = Awaited<ReturnType<PuppeteerModule['launch']>>

type BoqWithItems = Boq & { items: BoqItem[] }

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function buildHtml(boq: BoqWithItems): string {
  const rows = boq.items
    .map(
      (item, i) => `
        <tr>
            <td>${i + 1}</td>
            <td>${escapeHtml(item.productName)}</td>
            <td>${escapeHtml(item.description ?? '')}</td>
            <td>${escapeHtml(item.unit ?? '')}</td>
            <td>${item.quantity}</td>
        </tr>`,
    )
    .join('')

  return `
<style>
body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
.header { text-align: center; margin-bottom: 25px; }
.header h1 { margin: 0; color: #ff7b00; }
.header p { margin-top: 5px; color: #666; }
.info-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
.info-table td { border: 1px solid #ddd; padding: 10px; }
.boq-table { width: 100%; border-collapse: collapse; }
.boq-table th { background-color: #ff7b00; color: #fff; padding: 10px; border: 1px solid #ddd; }
.boq-table td { border: 1px solid #ddd; padding: 8px; }
.footer { margin-top: 40px; text-align: right; font-size: 11px; color: #777; }
</style>

<div class="header">
    <h1>Bill Of Quantities</h1>
    <p>ShowcaseIT Stock Management System</p>
</div>

<table class="info-table">
    <tr><td><strong>BOQ Number</strong></td><td>${escapeHtml(boq.boqNumber)}</td></tr>
    <tr><td><strong>Order Number</strong></td><td>${escapeHtml(boq.orderNumber)}</td></tr>
    <tr><td><strong>Name Of Event</strong></td><td>${escapeHtml(boq.eventName)}</td></tr>
    <tr><td><strong>Location</strong></td><td>${escapeHtml(boq.location)}</td></tr>
    <tr><td><strong>Date Created</strong></td><td>${boq.createdAt.toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short' })}</td></tr>
</table>

<table class="boq-table">
    <thead>
        <tr>
            <th style="width:5%">#</th>
            <th style="width:25%">Product Name</th>
            <th style="width:45%">Description</th>
            <th style="width:10%">Unit</th>
            <th style="width:15%">Quantity</th>
        </tr>
    </thead>
    <tbody>${rows}</tbody>
</table>

<div class="footer">Generated by ShowcaseIT</div>
`
}

let browserPromise: Promise<Browser> | null = null

async function getBrowser() {
  if (!browserPromise) {
    const puppeteer = await loadPuppeteer()
    // --no-sandbox is required in most containerized/shared hosting environments, where Chrome's
    // own OS-level sandboxing needs unprivileged user namespaces that the host doesn't grant.
    // --no-zygote/--disable-gpu trim Chrome's process/thread count, since Hostinger's sandbox
    // enforces a low ceiling that a normal Chrome launch exceeds (surfaced as a GLib "creating
    // thread ... Resource temporarily unavailable" crash — Linux EAGAIN from pthread_create).
    // (--single-process was tried too, but it's genuinely unstable in modern Chrome — GPU context
    // creation fails outright and crashes the connection — so it's deliberately not used here.)
    browserPromise = puppeteer
      .launch({
        headless: true,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--no-zygote',
          '--disable-gpu',
          '--disable-dev-shm-usage',
        ],
        dumpio: true,
      })
      .catch((err) => {
        browserPromise = null
        throw err
      })
  }
  return browserPromise
}

export async function renderBoqPdf(boq: BoqWithItems): Promise<Buffer> {
  const browser = await getBrowser()
  const page = await browser.newPage()
  try {
    await page.setContent(buildHtml(boq), { waitUntil: 'load' })
    const pdf = await page.pdf({ format: 'a4', printBackground: true })
    return Buffer.from(pdf)
  } finally {
    await page.close()
  }
}
