// Proforma invoice + payment receipt documents (MIGRATION_PLAN.md §34). Same layout language,
// company block and bank details as quotationPdf.ts (imported from there, not copied), rendered
// on demand through the same Browserless connection — nothing is stored, so a failed render never
// affects the underlying invoice/payment and retrying the download is always safe.

import type { PaymentMethod } from '#prisma-client'
import type { PaymentWithRelations, ProformaInvoiceWithRelations } from '../repositories/proformaInvoice.repository'
import { loadLogoDataUri } from './logo'
import { COMPANY_INFO_HTML, bankDetailsHtml, escapeHtml, formatQuantity, htmlToPdf, money, standaloneHtml } from './quotationPdf'

const STYLES = `
<style>
body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
.header { width: 100%; margin-bottom: 20px; }
.header td { vertical-align: top; }
.header h1 { margin: 0; color: #ff7b00; text-align: right; }
.header .company-info { font-size: 11px; color: #666; }
.customer-block { background: #fff7ef; border-left: 4px solid #ff7b00; padding: 8px 12px; margin-bottom: 15px; }
.customer-block .label { color: #ff7b00; font-weight: bold; font-size: 11px; }
.items-table { width: 100%; border-collapse: collapse; }
.items-table th { background-color: #ff7b00; color: #fff; padding: 8px; border: 1px solid #ddd; }
.items-table td { border: 1px solid #ddd; padding: 6px 8px; }
.totals-row td { font-weight: bold; background: #f8f9fa; }
.bottom-section { width: 100%; margin-top: 20px; }
.bottom-section td { vertical-align: top; }
.note { margin-top: 14px; font-size: 10.5px; color: #777; }
.footer { margin-top: 30px; text-align: right; font-size: 10px; color: #777; }
</style>`

const METHOD_LABELS: Record<PaymentMethod, string> = {
  Cash: 'Cash',
  BankTransfer: 'Bank Transfer',
  MobileMoney: 'Mobile Money',
  Card: 'Card',
  Cheque: 'Cheque',
  Other: 'Other',
}

const fmtDate = (d: Date) => d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })

// Matches quotationPdf's "$" prefix for the business's default USD; any other currency code is
// spelled out rather than guessing a symbol.
const amount = (currency: string, n: { toString(): string }) =>
  `${currency === 'USD' ? '$' : `${escapeHtml(currency)} `}${money(Number(n.toString()))}`

function header(title: string, metaRows: [string, string][], extraInfo: string) {
  const logoSrc = loadLogoDataUri()
  return `
<table class="header">
    <tr>
        <td style="width:55%;">
            ${logoSrc ? `<img src="${logoSrc}" alt="ShowcaseIT Logo" style="height:90px; margin-bottom:8px;">` : ''}
            <div class="company-info">
                ${COMPANY_INFO_HTML}${extraInfo}
            </div>
        </td>
        <td style="width:45%;">
            <h1>${title}</h1>
            <table style="width:100%; font-size:11px;">
                ${metaRows.map(([label, value]) => `<tr><td style="color:#888;">${label}</td><td style="text-align:right;">${escapeHtml(value)}</td></tr>`).join('')}
            </table>
        </td>
    </tr>
</table>`
}

function footer() {
  const logoSrc = loadLogoDataUri()
  return `
<div class="footer">
    Generated by ShowcaseIT${logoSrc ? ` <img src="${logoSrc}" alt="ShowcaseIT Logo" style="height:16px; vertical-align:middle; margin-left:6px;">` : ''}
</div>`
}

function customerBlock(customerName: string, projectName: string | null) {
  return `
<div class="customer-block">
    <div class="label">BILL TO</div>
    <div><strong>${escapeHtml(customerName)}</strong></div>
    ${projectName ? `<div>${escapeHtml(projectName)}</div>` : ''}
</div>`
}

function buildInvoiceHtml(inv: ProformaInvoiceWithRelations): string {
  const cur = inv.currency
  const rows = inv.items
    .map(
      (item) => `
        <tr>
            <td>${escapeHtml(item.description)}</td>
            <td style="text-align:right;">${formatQuantity(Number(item.quantity))}</td>
            <td style="text-align:right;">${amount(cur, item.unitPrice)}</td>
            <td style="text-align:right;">${amount(cur, item.lineTotal)}</td>
        </tr>`,
    )
    .join('')
  const balance = inv.total.minus(inv.amountPaid)

  return `${STYLES}
${header(
  'PROFORMA INVOICE',
  [
    ['Date', fmtDate(inv.issuedAt)],
    ['Invoice #', inv.invoiceNumber],
    ['Quotation #', inv.quotation.quotationNumber],
    ['Order #', inv.orderNumber || '-'],
    ['Customer ID', inv.customerId || '-'],
  ],
  '',
)}
${customerBlock(inv.customerName, inv.projectName)}

<table class="items-table">
    <thead>
        <tr>
            <th style="width:45%">Description</th>
            <th style="width:15%">Quantity</th>
            <th style="width:20%">Unit Price</th>
            <th style="width:20%">Amount</th>
        </tr>
    </thead>
    <tbody>
${rows}
        <tr class="totals-row">
            <td colspan="3" style="text-align:right;">Subtotal</td>
            <td style="text-align:right;">${amount(cur, inv.subtotal)}</td>
        </tr>
        ${
          inv.applyVat
            ? `<tr class="totals-row">
            <td colspan="3" style="text-align:right;">VAT (15.5%)</td>
            <td style="text-align:right;">${amount(cur, inv.vatAmount)}</td>
        </tr>`
            : ''
        }
        <tr class="totals-row">
            <td colspan="3" style="text-align:right;">TOTAL</td>
            <td style="text-align:right;">${amount(cur, inv.total)}</td>
        </tr>
        ${
          inv.amountPaid.gt(0)
            ? `<tr class="totals-row">
            <td colspan="3" style="text-align:right;">Amount Paid</td>
            <td style="text-align:right;">${amount(cur, inv.amountPaid)}</td>
        </tr>
        <tr class="totals-row">
            <td colspan="3" style="text-align:right;">BALANCE DUE</td>
            <td style="text-align:right;">${amount(cur, balance)}</td>
        </tr>`
            : ''
        }
    </tbody>
</table>

<table class="bottom-section">
    <tr>
        <td style="width:58%;">
            <strong style="color:#ff7b00;">Terms &amp; Conditions</strong>
            <div style="white-space:pre-wrap; font-size:11px; margin-top:4px;">${escapeHtml(inv.termsConditions)}</div>
        </td>
        <td style="width:42%;">
            <strong style="color:#ff7b00;">Bank Details</strong>
            ${bankDetailsHtml()}
        </td>
    </tr>
</table>

<div class="note">This proforma invoice is a request for payment, not a receipt. Please quote invoice ${escapeHtml(inv.invoiceNumber)} as your payment reference.</div>
${footer()}
`
}

function buildReceiptHtml(p: PaymentWithRelations): string {
  const inv = p.invoice
  const cur = inv.currency
  const recordedBy = `${p.recordedBy.name} ${p.recordedBy.surname}`.trim()

  return `${STYLES}
${header(
  'PAYMENT RECEIPT',
  [
    ['Receipt #', p.receiptNumber],
    ['Payment Date', fmtDate(p.paymentDate)],
    ['Invoice #', inv.invoiceNumber],
    ['Quotation #', inv.quotation.quotationNumber],
    ['Order #', inv.orderNumber || '-'],
  ],
  `<br>Received by: ${escapeHtml(recordedBy || '-')}`,
)}
${customerBlock(inv.customerName, inv.projectName)}

<table class="items-table">
    <thead>
        <tr>
            <th style="width:60%">Details</th>
            <th style="width:40%">Value</th>
        </tr>
    </thead>
    <tbody>
        <tr><td>Payment method</td><td style="text-align:right;">${METHOD_LABELS[p.method]}</td></tr>
        <tr><td>Payment reference</td><td style="text-align:right;">${escapeHtml(p.reference || '-')}</td></tr>
        <tr><td>Invoice total</td><td style="text-align:right;">${amount(cur, inv.total)}</td></tr>
        <tr class="totals-row"><td>AMOUNT RECEIVED (this payment)</td><td style="text-align:right;">${amount(cur, p.amount)}</td></tr>
        <tr class="totals-row"><td>Balance remaining after this payment</td><td style="text-align:right;">${amount(cur, p.balanceAfter)}</td></tr>
    </tbody>
</table>
${p.notes ? `<div style="margin-top:12px;"><strong style="color:#ff7b00;">Notes</strong><div style="white-space:pre-wrap; font-size:11px; margin-top:4px;">${escapeHtml(p.notes)}</div></div>` : ''}

<div class="note">This receipt covers only the single payment shown above. Issued ${escapeHtml(p.createdAt.toLocaleString('en-GB'))}.</div>
${footer()}
`
}

export const renderInvoicePdf = (inv: ProformaInvoiceWithRelations) => htmlToPdf(buildInvoiceHtml(inv))
export const renderInvoiceHtml = (inv: ProformaInvoiceWithRelations) =>
  standaloneHtml(`Proforma Invoice ${inv.invoiceNumber}`, buildInvoiceHtml(inv))

export const renderReceiptPdf = (p: PaymentWithRelations) => htmlToPdf(buildReceiptHtml(p))
export const renderReceiptHtml = (p: PaymentWithRelations) => standaloneHtml(`Receipt ${p.receiptNumber}`, buildReceiptHtml(p))
