// Client-facing PDF export for the AI Takeoff / BOQ Generator — mirrors quotationPdf.ts's
// structure/helpers exactly (same escapeHtml/money, same getBrowser()/loadLogoDataUri() reuse,
// same page.pdf() call), grouped by category, with no source/confidence/notes columns since this
// document goes to the client, not back into the review workflow.

import type { TakeoffDesign, TakeoffItem } from '#prisma-client'
import { getBrowser } from './pdfBrowser'
import { loadLogoDataUri } from './logo'

type DesignWithItems = TakeoffDesign & { items: TakeoffItem[]; project: { name: string; clientName: string | null } }

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function formatQuantity(n: number) {
  return n.toFixed(2).replace(/0+$/, '').replace(/\.$/, '')
}

function buildHtml(design: DesignWithItems): string {
  const logoSrc = loadLogoDataUri()

  const byCategory = new Map<string, TakeoffItem[]>()
  for (const item of design.items) {
    const list = byCategory.get(item.category) ?? []
    list.push(item)
    byCategory.set(item.category, list)
  }

  const sections = [...byCategory.entries()]
    .map(
      ([category, items]) => `
        <tr><td colspan="4" style="background:#fff7ef; color:#ff7b00; font-weight:bold; padding:6px 8px;">${escapeHtml(category)}</td></tr>
        ${items
          .map(
            (item) => `
        <tr>
            <td>${escapeHtml(item.description)}</td>
            <td style="text-align:right;">${formatQuantity(Number(item.quantity))} ${escapeHtml(item.unit)}</td>
            <td style="text-align:right;">${[item.widthMm, item.heightMm, item.lengthMm].filter((v) => v != null).map((v) => `${Number(v)}mm`).join(' × ') || '-'}</td>
            <td>${escapeHtml(item.material ?? '-')}</td>
        </tr>`,
          )
          .join('')}`,
    )
    .join('')

  return `
<style>
body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
.header { width: 100%; margin-bottom: 20px; }
.header td { vertical-align: top; }
.header h1 { margin: 0; color: #ff7b00; text-align: right; }
.header .company-info { font-size: 11px; color: #666; }
.customer-block { background: #fff7ef; border-left: 4px solid #ff7b00; padding: 8px 12px; margin-bottom: 15px; }
.customer-block .label { color: #ff7b00; font-weight: bold; font-size: 11px; }
.items-table { width: 100%; border-collapse: collapse; }
.items-table th { background-color: #ff7b00; color: #fff; padding: 8px; border: 1px solid #ddd; }
.items-table td { border: 1px solid #ddd; padding: 6px 8px; }
.footer { margin-top: 30px; text-align: right; font-size: 10px; color: #777; }
</style>

<table class="header">
    <tr>
        <td style="width:55%;">
            ${logoSrc ? `<img src="${logoSrc}" alt="ShowcaseIT Logo" style="height:55px; margin-bottom:8px;">` : ''}
            <div class="company-info">
                32 Jacana Drive, Greystone Park, Harare<br>
                Phone: +263 772 548792<br>
                VAT Number: 220097572<br>
                TIN Number: 2001387234
            </div>
        </td>
        <td style="width:45%;">
            <h1>BILL OF QUANTITIES</h1>
            <table style="width:100%; font-size:11px;">
                <tr><td style="color:#888;">Date</td><td style="text-align:right;">${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}</td></tr>
                <tr><td style="color:#888;">Project</td><td style="text-align:right;">${escapeHtml(design.project.name)}</td></tr>
            </table>
        </td>
    </tr>
</table>

${
  design.project.clientName
    ? `<div class="customer-block">
    <div class="label">CLIENT</div>
    <div><strong>${escapeHtml(design.project.clientName)}</strong></div>
</div>`
    : ''
}

<table class="items-table">
    <thead>
        <tr>
            <th style="width:40%">Description</th>
            <th style="width:20%">Quantity</th>
            <th style="width:20%">Dimensions</th>
            <th style="width:20%">Material</th>
        </tr>
    </thead>
    <tbody>
${sections}
    </tbody>
</table>

<div class="footer">
    Generated by ShowcaseIT${logoSrc ? ` <img src="${logoSrc}" alt="ShowcaseIT Logo" style="height:16px; vertical-align:middle; margin-left:6px;">` : ''}
</div>
`
}

export async function renderTakeoffQuotationPdf(design: DesignWithItems): Promise<Buffer> {
  const browser = await getBrowser()
  const page = await browser.newPage()
  try {
    await page.setContent(buildHtml(design), { waitUntil: 'load' })
    const pdf = await page.pdf({ format: 'a4', printBackground: true })
    return Buffer.from(pdf)
  } finally {
    await page.close()
  }
}
